int readfile(const char*  filenamet);
int splitline(char* line, char columns[MAX_COLUMNS][MAX_LENGTH],char units[MAX_COLUMNS][MAX_LENGTH] );
void add2table(double ** table, char* line, int linenum );
void allocateincoord(int linecount);
void setreadin(int coordorder, int column, double ** table, double multifactor, int realcoord);
void checkifenergyset(int entype);
void checkiftimeset(int entype);
void checkifangset(int entype);
void calculaterefparam();
void convert2standard();
void add2internaltab(char* word, char columns[MAX_COLUMNS][MAX_LENGTH], char units[MAX_COLUMNS][MAX_LENGTH], int count) ;
double getEnergyUnit(char *unit);
double getMetricUnit(char *unit);
void fillcoordstructure(int numcolum, char columns[MAX_COLUMNS][MAX_LENGTH], char units[MAX_COLUMNS][MAX_LENGTH], double **table);
void free_readin_memory(double **table);
void checkinputtype();
void deallocateincoord();
void allocateincoord();