//void print2file();
//void printdistsettings_(int *ndist);
//int getnumberdist_();
//int getupperbound();
//void getcoordvectors_(double *x, double *xp, double *y, double *yp, double *sigma, double *delta);
//void getcoord_(double coordinate[6], int initial );
//void getcoord_normalized(double coordinate_normalized[6], int initial );
//void getcoord2_(double coordinate[6], int *initial );
//void print2fort13();
void print2file(const char* nameoffile);