#! /usr/bin/env bash
set -ex

mkdir build
cd build

: ${PY:=/opt/python/cp36-cp36m/bin}

$PY/pip install --upgrade cmake
$PY/cmake .. \
    -DBUILD_SHARED_LIBS=OFF \
    -DMADX_STATIC=ON \
    -DCMAKE_INSTALL_PREFIX=../dist \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="-fvisibility=hidden -flto" \
    -DCMAKE_CXX_FLAGS="-fvisibility=hidden -flto" \
    -DCMAKE_Fortran_FLAGS="-fvisibility=hidden -flto" \
    -DMADX_INSTALL_DOC=OFF \
    -DMADX_ONLINE=OFF \
    -DMADX_FORCE_32=OFF \
    -DMADX_X11=OFF

$PY/cmake --build . --target install

[[ $(arch) == i686 ]] && ARCH=32 || ARCH=64

cd ..
# on 32bit, we get 'madx32', on 64bit just 'madx':
if [[ -f dist/bin/madx$ARCH ]]; then
    ln -sf dist/bin/madx$ARCH madx$ARCH
else
    ln -sf dist/bin/madx madx$ARCH
fi
ln -sf dist/bin/ndiff numdiff$ARCH
