pdflatex f-drf.tex  
pdflatex f-ermoni.tex  
pdflatex f-glob.tex  
pdflatex f-rbnd.tex  
pdflatex f-ref.tex  
pdflatex f-sbnd.tex  
pdflatex f-xsdisp.tex  
pdflatex f-xydisp.tex  
pdflatex f-ysdisp.tex
