# |
# o---------------------------------------------------------------------o
# |
# | MAD GC makefile
# |
# o---------------------------------------------------------------------o
# |
# | Methodical Accelerator Design
# |
# | Copyright (c) 2011+ CERN, mad@cern.ch
# |
# | For more information, see http://cern.ch/mad
# |
# o---------------------------------------------------------------------o
# |
# | $Id$
# |

###################
# Project settings

PROJECT  := libgc

####################
# Makefile includes

makedir := ../../make
include $(makedir)/make.inc

# end of makefile
