# |
# o---------------------------------------------------------------------o
# |
# | MAD GC makefile
# |
# o---------------------------------------------------------------------o
# |
# | Methodical Accelerator Design
# |
# | Copyright (c) 2011+ CERN, mad@cern.ch
# |
# | For more information, see http://cern.ch/mad
# |
# o---------------------------------------------------------------------o
# |
# | $Id$
# |

###################
# Project settings

PROJECT  := libgc

#################
# Build settings
#

# architecture bit: detect/32/64 (default is detect)
ARCH    := detect

# debugging mode: yes/no (default is no)
DEBUG   := no

# profiling mode: yes/no (default is no)
PROFILE := no

# make shared lib: yes/no (default is no)
SHARED  := no

####################
# Makefile includes

makedir := ../../make
include $(makedir)/make.inc

# end of makefile
