#! /usr/bin/env bash

# Sets a (multi-line) output of the current step.
# Usage: set-output <name> <value>
name=$1
value=$2
delim=EOS_$(openssl rand -hex 16)

echo >>"$GITHUB_OUTPUT" "$name<<$delim"
echo >>"$GITHUB_OUTPUT" "$value"
echo >>"$GITHUB_OUTPUT" "$delim"
