#! /usr/bin/env bash

# Sets a (multi-line) output of the current step.
# Usage: set-output <name> <value>
name=$1
value=$2

# Escape '\n', '\r', '%' to make this work with multi-line strings, see:
# https://github.community/t/set-output-truncates-multiline-strings/16852
value="${value//'%'/'%25'}"
value="${value//$'\n'/'%0A'}"
value="${value//$'\r'/'%0D'}"

echo "::set-output name=$name::$value"
